backend:
  name: github
  repo: patricoferris/mirage-site
  base_url: https://patricoferris.com
  branch: master

publish_mode: editorial_workflow
media_folder: "static/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Slugified Title 
    fields: # The fields for each document, usually in front matter
      - label: "Authors"
        name: "authors"
        collapsed: false
        widget: "list"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Updated", name: "updated", format: "LLL", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", widget: "datetime"}
      - label: "Tags"
        name: "tags"
        collapsed: true
        widget: "list"
      - {label: "Body", name: "body", widget: "markdown"}
